config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#index'
    # get '/cleaners/sign_in', to: 'devise/sessions#new'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path: '', path_names: { sign_in: 'cleaners/sign_in', sign_out: '/users/sign_out' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post '/register/cleaner', to: 'users/registrations#create_cleaner'
  end

  mount Resque::Server, at: "/resque"
  # For running resque queues it must be redis server running
  # Run this line in terminal
  # QUEUE=* rake resque:work

  namespace :cleaners do
    get "/dashboard", to: "dashboard#index"
    get '/calendar', to: "bookings#calendar"
    get "/calendar/booking", to: "bookings#get_booking"
    get "/calendar/bookings", to: "bookings#get_bookings"
    resources :bookings do 
      post 'cancel_booking', to: "bookings#cancel_booking", on: :member
      post 'accept_booking', to: "bookings#accept_booking", on: :member
      post 'decline_booking', to: "bookings#decline_booking", on: :member
      get 'email_booking', to: "bookings#email_bookings", on: :collection
      get 'previous', to: "bookings#previous",  on: :collection
    end
  end

  resources :cleaners do
    get "/back_to_admin", to: "cleaners#back_to_admin", as: "back_to_admin", on: :collection
    get "/destroy_admin_session", to: "cleaners#destroy_admin_session", as: "destroy_admin_session", on: :collection
  end

  scope '/webhooks' do
    post 'new_booking', to: 'webhooks#new_booking'
    post 'cancel_booking', to: 'webhooks#cancel_booking'
    post 'complete_booking', to: 'webhooks#complete_booking'
    post 'update_booking', to: 'webhooks#update_booking'
  end
end

app/models/cleaner.rb
class Cleaner < ApplicationRecord
  include Importable
  include Filters
  acts_as :user
  # Companies
  has_many :cleaner_companies
  has_many :companies, through: :cleaner_companies, dependent: :destroy
  # Bookings
  has_many :cleaner_bookings
  has_many :bookings, through: :cleaner_bookings
  belongs_to :permission, optional: true
  #Penalties
  has_many :penalties
  accepts_nested_attributes_for :companies
  validates :address, :postal_code, :state, :city, :role, presence: true
  validates :max_bookings, numericality: { greater_than: 0, less_than_or_equal_to: 3 }
  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  after_save :get_full_name

  TimeZones = { 
    "International Date Line West" => 1, 
    "Midway Island" => 2, 
    "Hawaii" => 3, 
    "Alaska" => 4, 
    "Pacific Time (US & Canada)" => 5, 
    "Tijuana" => 6, 
    "Mountain Time (US & Canada)" => 7, 
    "Arizona" => 8, 
    "Central Time (US & Canada)" => 9,
    "Eastern Time (US & Canada)" => 10, 
    "Indiana (East)" => 11, 
    "Atlantic Time (Canada)" => 12, 
    "UTC" => 13,
  }
  enum timezone: TimeZones, _suffix: true

  def get_requested_bookings
    # Does not show if time of booking - requested_booking_limit is more than time now.
    # A cron job will deleted the requested booking to put it back in the pool 
    self.bookings.where(["requested = ? AND DATE(booking_date) >= ?", true, Date.today]).select{|b| Time.current < b.booking_date - Config.fetch('requested_booking_limit').to_i.hours }
  end

  #Show Previos bookings Assigned
  def get_previous_bookings
    return self.bookings.where(["DATE(booking_date) <= ? ", 
      Date.today - 1.day ]).order(:booking_date)
  end

  # show the bookings assigned for today.
  def get_todays_bookings
    return self.bookings.where(["DATE(booking_date) <= ? AND DATE(booking_date) >= ?  AND requested = ?", 
      Date.today + 1.day, Date.today - 1.day, false ]).order(:booking_date).select{ |booking| 
      booking.booking_date.localtime.to_date ==  Time.now.to_date }
  end

  def get_assigned_bookings_for_tomorrow
    return self.bookings.where(["DATE(booking_date) >= ? AND requested = ?", Date.today - 1, false ]).order(:booking_date).
    select{ |booking| booking.booking_date.localtime.to_date ==  Time.now.to_date + 1 }
  end

  def get_tomorrow_bookings
    return self.bookings.where(["DATE(booking_date) <= ? AND DATE(booking_date) >= ? AND requested = ?", 
      Time.now.localtime.to_date.end_of_day + 2.days, Time.now.localtime.to_date + 2.day, false])
  end

  def get_bookings_by_date(start_time, end_time)
    return self.bookings.where(["DATE(booking_date) <= ? AND DATE(booking_date) >= ? AND requested = ?", 
      start_time, end_time, false])
  end

  # show tomorrows_available bookings
  def available_bookings(from: nil, to: nil)
    start_time = from ? from : Time.now.localtime.beginning_of_day + 2.days
    end_time = to ? to : Time.now.localtime.end_of_day + 2.days
    ready_tomorrow_booking_time = {}
    ready_tomorrow_booking_time[:max] = self.get_tomorrow_bookings.blank? ? false : self.get_tomorrow_bookings.order(booking_date: :desc).first.booking_date.localtime + 4.hours
    ready_tomorrow_booking_time[:min] = self.get_tomorrow_bookings.blank? ? false : self.get_tomorrow_bookings.order(booking_date: :asc).first.booking_date.localtime - 4.hours
    companies = self.companies.empty? ? '(0)' : self.companies.pluck(:id).to_s.tr('[]', '()')
    bookings = Booking.where(
      ["company_id IN #{companies} AND booking_date >= ? AND booking_date <= ? AND booking_assigned = ? AND cancelled = ? AND archived = ? AND requested = ?", 
       start_time, end_time, false, false, false, false ]
    ).order(:booking_date)
    unless ready_tomorrow_booking_time[:max].blank? || ready_tomorrow_booking_time[:min].blank?
      bookings = bookings.select{|b| b.booking_date.localtime.to_time >= ready_tomorrow_booking_time[:max].to_time || b.booking_date.localtime.to_time <= ready_tomorrow_booking_time[:min].to_time }
    end
    return bookings
  end

  def pick_booking(booking)
    booking.booking_assigned = true
    self.bookings << booking
    booking.calculate_fees
    Manager.all.map {|manager| BookingMailer.notify_claimed_booking_to_managers(manager, booking, self).deliver}
  end

  #Check if cleaner can claim booking base on max number of bookings he/she can take
  def can_claim_booking?
    today_bookings =  self.bookings.where(["DATE(booking_date) <= ? AND DATE(booking_date) >= ? AND requested = ? ", Date.today + 2, Date.today - 1, false ])
    .select{|b| b.booking_date.localtime.to_date == Date.today + 2}.count
    return today_bookings < self.max_bookings
  end

  # Check if they have permissions to see the bookings
  def has_permission_to_view?
    return false if !self.permission
    return Time.current.utc.in_time_zone(self.timezone).strftime( "%H%M%S%N" ) >= (self.permission.hour + ':' + self.permission.minutes).to_time.strftime( "%H%M%S%N" ) if self.permission.hour && self.permission.minutes 
  end

  def cut_of_time
    return (Time.current.utc.in_time_zone(self.timezone) + 1.day ).change({ hour: Config.fetch('cut_of_time').to_i }) >= Time.current.utc.in_time_zone(self.timezone)
  end

  def bookings_left_to_claim
    return max_bookings - get_tomorrow_bookings.count
  end

  def bookings_left_to_claim_by_date(time_start, time_end)
    number_of_bookings = get_bookings_by_date(time_start, time_end).count
    return max_bookings - number_of_bookings
  end


  def email_today_bookings(bookings)
    bookings = Booking.find(bookings)
    BookingMailer.email_today_bookings(self, bookings).deliver
  end

  def email_tomorrow_bookings(bookings)
    bookings = Booking.find(bookings)
    BookingMailer.email_tomorrow_bookings(self, bookings).deliver
  end

  private

  def get_full_name
    full_name = "#{first_name} #{last_name}"
    self.update_column(:full_name, full_name)
  end
end

app/controllers/cleaners/bookings_controller.rb
class Cleaners::BookingsController < ApplicationController
  before_action :set_booking, only: [:update, :show, :cancel_booking, :accept_booking, :decline_booking, :get_booking]

  def index
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = Kaminari.paginate_array(@cleaner.available_bookings).page(params[:page]).per(20)
    if params[:from] && params[:to]
      time = Time.current + 1.day
      @bookings = Kaminari.paginate_array(@cleaner.available_bookings(from: time.change( hour: params['from']), to: time.change( hour: params['to']))).page(params[:page]).per(20)
    end
  end

  def show
    @cleaner = Cleaner.find(current_user.actable_id)
  end

  def update
    # Check if booking has not been taken yet
    cleaner = Cleaner.find(current_user.actable_id)
    if @booking.booking_assigned
      flash[:warning] = "This Booking has already been taken."
      redirect_to cleaners_bookings_path
    else
      if cleaner.can_claim_booking?
        cleaner.pick_booking(@booking)
        if @booking.save
          flash[:success] = "Booking Claimed Succesfully."
          redirect_to cleaners_bookings_path
        else
          flash[:success] = "Error claiming this booking."
          redirect_to cleaners_bookings_path
        end
      else
        flash[:warning] = "You have reached your max amount of bookings for tomorrow."
        redirect_to cleaners_bookings_path
      end
    end
  end

  def cancel_booking
    @booking.cancel_booking
    if @booking.save
      flash[:success] = "You have cancel the booking successfully."
      redirect_to cleaners_dashboard_path
    end
  end

  def previous
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = Kaminari.paginate_array(@cleaner.get_previous_bookings).page(params[:page]).per(20)
  end

  def calendar
  end

  def get_bookings
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = @cleaner.bookings
  end

  def get_booking
    @cleaner = Cleaner.find(current_user.actable_id)
    booking_html = render_to_string(:template => 'cleaners/bookings/_claim_booking.html.erb', :layout => false, :locals => { :booking => @booking })
    render :json => { :booking_html => booking_html }, :status => :ok
  end

  def email_bookings
    unless params['bookings'] == nil
      if params['date'] == 'today'
        Cleaner.find(current_user.actable_id).email_today_bookings(params['bookings'])
      else
        Cleaner.find(current_user.actable_id).email_tomorrow_bookings(params['bookings'])
      end
    end
    flash[:success] = "You bookings were emailed succesfully. Please review your email."
    redirect_to cleaners_dashboard_path
  end

  def accept_booking
    @booking.accept_request(current_user)
    if @booking.save
      flash[:success] = "You have succesfully accepted the customer request."
      redirect_to cleaners_dashboard_path
    end
  end

  def decline_booking
    @booking.decline_request(current_user)
    if @booking.save
      flash[:success] = "You have declined the customer request."
      redirect_to cleaners_dashboard_path
    end
  end

  private
    
  def set_booking
    @booking = Booking.find_by(id: params[:id])
  end
end

app/controllers/cleaners/dashboard_controller.rb
class Cleaners::DashboardController < ApplicationController
  
  def index 
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = @cleaner.get_todays_bookings
    @future_bookings = @cleaner.get_assigned_bookings_for_tomorrow
  end
end

app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
	before_action :set_cleaner, only: [:edit, :update]

  def edit
  end

  def update
    if params[:cleaner][:password].blank? && params[:cleaner][:password_confirmation].blank?
      params[:cleaner].delete("password")
      params[:cleaner].delete("password_confirmation")
    end
    respond_to do |format|
      if @cleaner.update(cleaner_params)
        flash[:notice] = 'Cleaner was updated succesfully'
        format.html { redirect_to edit_cleaner_path(@cleaner) }
      else
        flash[:error] = @cleaner.errors
        format.html { render :edit }
      end
    end
  end

  def back_to_admin
    cleaner_user = current_user
    sign_out(cleaner_user)
    session["cleaner_session_id"] = nil
    admin = User.find(session["admin_session_id"])
    sign_in(:user, admin)
    redirect_to admin_dashboard_path
  end

  def destroy_admin_session
    @current_user = Cleaner.find(session["cleaner_session_id"])
    sign_out_and_redirect(@current_user)
  end

  private
    
    def set_cleaner
      @cleaner = Cleaner.find_by(id: current_user.actable_id)
    end

    def cleaner_params
      params.require(:cleaner).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :address, :postal_code, :state, :city, :max_bookings, :rating, :timezone, :role )
    end
end

app/views/cleaners/edit.html.erb
<!-- Body -->
<section class="app-content">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-login">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-12">
                <%= link_to "Edit profile", "#", id: "register-form-link", class: 'active' %>
              </div>
            </div>
            <hr>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-lg-12">
                <%= simple_form_for @cleaner, :url => cleaner_path(current_user), method: "patch", :html => { id: "register-form", style: "display:'block';", role: "form", class: nil } do |f| %>
                  <% unless flash[:error].blank? %>
                  <div class="alert alert-danger %>  " role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <ul>
                    <% if flash[:error] %>
                        <% flash[:error].each do |item, m| %>
                          <li>
                            <%= item.to_s.humanize %> <%= m %>
                          </li>
                        <% end %>
                    <% end %>
                    </ul>
                  </div>
                  <% end %>
                  <% unless flash[:notice].blank? %>
                  <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <ul>
                      <li>
                        <%= flash[:notice] %>
                      </li>
                    </ul>
                  </div>
                  <% end %>
                  <div class="form-inputs">
                    <%= f.input :first_name, required: true, autofocus: true, tabindex: "1", class: "form-control", placeholder: "First name" %>
                    <%= f.input :last_name, required: true, autofocus: true, tabindex: "2", class: "form-control", placeholder: "Last name" %>
                    <%= f.input :email, required: true, autofocus: true, tabindex: "3", class: "form-control", placeholder: "Email Address" %>
                    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), tabindex: "2", class: "form-control", placeholder: "Password" %>
                    <%= f.input :password_confirmation, label: false, required: true, tabindex: "4", class: "form-control", placeholder: "Confirm Password" %>

                    <%= f.input :phone_number, required: true, tabindex: "5", class: "form-control", placeholder: "Phone number" %>
                    <%= f.input :address, required: true, tabindex: "6", class: "form-control", placeholder: "Address" %>
                    <%= f.input :postal_code, required: true, tabindex: "7", class: "form-control", placeholder: "Postal code" %>
                    <%= f.input :state, required: true, tabindex: "8", class: "form-control", placeholder: "State" %>
                    <%= f.input :city,  required: true, tabindex: "9", class: "form-control", placeholder: "City" %>

                    <%= f.select :timezone, Cleaner.timezones.keys, {include_blank: 'Select a Timezone'}, label: false, required: true, tabindex: "10", class: "form-control" %>
                    <br>
                    <%= f.input :role, :input_html => { :value => :cleaner }, as: :hidden %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-sm-9">
                        <%= f.submit "Save profile", tabindex: "4", class: "btn-save-cleaner btn btn-success" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>