config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#index'
    # get '/cleaners/sign_in', to: 'devise/sessions#new'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path: '', path_names: { sign_in: 'cleaners/sign_in', sign_out: '/users/sign_out' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post '/register/cleaner', to: 'users/registrations#create_cleaner'
  end

  mount Resque::Server, at: "/resque"
  # For running resque queues it must be redis server running
  # Run this line in terminal
  # QUEUE=* rake resque:work

  namespace :cleaners do
    get "/dashboard", to: "dashboard#index"
    get '/calendar', to: "bookings#calendar"
    get "/calendar/booking", to: "bookings#get_booking"
    get "/calendar/bookings", to: "bookings#get_bookings"
    resources :bookings do 
      post 'cancel_booking', to: "bookings#cancel_booking", on: :member
      post 'accept_booking', to: "bookings#accept_booking", on: :member
      post 'decline_booking', to: "bookings#decline_booking", on: :member
      get 'email_booking', to: "bookings#email_bookings", on: :collection
      get 'previous', to: "bookings#previous",  on: :collection
    end
  end

  resources :cleaners do
    get "/back_to_admin", to: "cleaners#back_to_admin", as: "back_to_admin", on: :collection
    get "/destroy_admin_session", to: "cleaners#destroy_admin_session", as: "destroy_admin_session", on: :collection
  end

  scope '/webhooks' do
    post 'new_booking', to: 'webhooks#new_booking'
    post 'cancel_booking', to: 'webhooks#cancel_booking'
    post 'complete_booking', to: 'webhooks#complete_booking'
    post 'update_booking', to: 'webhooks#update_booking'
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_paper_trail
  include Twiliable
  belongs_to :property
  belongs_to :company
  belongs_to :location
  has_many :cleaner_bookings
  has_many :cleaners, through: :cleaner_bookings
  has_many :booking_services
  has_many :services, through: :booking_services
  validates :booking_date, presence: true
  # after_save :calculate_fees
  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  after_save :notify_cancellation
  after_save :notify_requested_bookings
  #Penalties
  has_many :penalties

  scope :claimed, -> { where(booking_assigned: true) }
  scope :cancelled, -> { where(cancelled: true) }
  scope :not_cancelled, -> { where(cancelled: false) }
  scope :left_to_claime, -> { where(booking_assigned: false) }
  scope :not_hidden, -> { where(hidden: false) }
  
  def calculate_fees
    service_total =  self.services.select { |service| service.service_type != 'add_on' }.pluck(:price).inject(0){|sum,x| sum + x }
    extras_total = self.services.select { |service| service.service_type == 'add_on' }.pluck(:price).inject(0){|sum,x| sum + x }
    sub_total = service_total + extras_total
    sales_tax = sub_total * ( self.location.tax.to_f / 100 )
    final_amount = sub_total + sales_tax
    self.update_column(:service_total, service_total)
    self.update_column(:extras_total, extras_total)
    self.update_column(:sub_total, sub_total)
    self.update_column(:sales_tax, sales_tax)
    self.update_column(:final_amount, final_amount)
    self.cleaner_bookings.each do |cb|
      earnings = final_amount.to_f * (cb.cleaner.percentage_of_booking.to_f/100)
      cb.update_column(:earnings,earnings)
    end
  end

  def cancel_booking
    if !self.can_cancel_booking?      
      amount = Config.fetch('cancelation_penalty_amount') ? Config.fetch('cancelation_penalty_amount') : 0
      self.cleaners.map {|cleaner| Penalty.create!(amount: amount, cleaner: cleaner, booking: self) }
      Manager.all.map {|manager| BookingMailer.notify_cancelation_to_managers(manager, self).deliver  }
    end
    self.booking_assigned = false
    self.cleaners.destroy_all
  end

  def can_cancel_booking?
    return Config.fetch('cancelation_penalty_time') ? ((self.booking_date - Time.current) / 3600) >= Config.fetch('cancelation_penalty_time').to_i : true
  end

	def notify_cancellation
		if self.cancelled == true && !self.cleaners.empty?
			self.cleaners.map { |cleaner| BookingMailer.notify_cancelation(cleaner, self).deliver  }
			notify_cancelation_via_text(self.cleaners, self)
			self.booking_assigned = false
      self.cleaners.destroy_all
		end
	end

  def check_expired_requested_bookings
    bookings = Booking.where(requested: true)
    bookings.each do |booking|
      if Time.current > (booking.booking_date - Config.fetch('requested_booking_limit').to_i.hours - 1.days)
        booking.update_column(:booking_assigned, false)
        booking.update_column(:requested, false)
        Manager.all.map {|manager| BookingMailer.notify_booking_not_accepted_to_managers(manager, booking).deliver}
        booking.cleaners.destroy_all
      end
    end
    Rails.logger.info("Check Requested updated at #{Time.now}")
  end

  def notify_requested_bookings
    if self.requested == true && !self.cleaners.empty?
      self.cleaners.map { |cleaner| BookingMailer.email_customer_request(cleaner, self).deliver }
      notify_booking_request(self.cleaners, self)
    end
  end

  def accept_request(cleaner)
    self.booking_assigned = true
    self.requested = false
    Manager.all.map {|manager| BookingMailer.notify_claimed_booking_to_managers(manager, self, cleaner).deliver}
  end

  def decline_request(declined_cleaner)
    Manager.all.map {|manager| BookingMailer.notify_declined_booking_to_managers(manager, self, declined_cleaner).deliver}
    self.booking_assigned = false
    self.requested = false
    self.cleaners.destroy_all
  end

  def is_past_booking?
    return self.booking_date < Time.current
  end
end

app/controllers/cleaners/bookings_controller.rb
class Cleaners::BookingsController < ApplicationController
  before_action :set_booking, only: [:update, :show, :cancel_booking, :accept_booking, :decline_booking, :get_booking]

  def index
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = Kaminari.paginate_array(@cleaner.available_bookings).page(params[:page]).per(20)
    if params[:from] && params[:to]
      time = Time.current + 1.day
      @bookings = Kaminari.paginate_array(@cleaner.available_bookings(from: time.change( hour: params['from']), to: time.change( hour: params['to']))).page(params[:page]).per(20)
    end
  end

  def show
    @cleaner = Cleaner.find(current_user.actable_id)
  end

  def update
    # Check if booking has not been taken yet
    cleaner = Cleaner.find(current_user.actable_id)
    if @booking.booking_assigned
      flash[:warning] = "This Booking has already been taken."
      redirect_to cleaners_bookings_path
    else
      if cleaner.can_claim_booking?
        cleaner.pick_booking(@booking)
        if @booking.save
          flash[:success] = "Booking Claimed Succesfully."
          redirect_to cleaners_bookings_path
        else
          flash[:success] = "Error claiming this booking."
          redirect_to cleaners_bookings_path
        end
      else
        flash[:warning] = "You have reached your max amount of bookings for tomorrow."
        redirect_to cleaners_bookings_path
      end
    end
  end

  def cancel_booking
    @booking.cancel_booking
    if @booking.save
      flash[:success] = "You have cancel the booking successfully."
      redirect_to cleaners_dashboard_path
    end
  end

  def previous
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = Kaminari.paginate_array(@cleaner.get_previous_bookings).page(params[:page]).per(20)
  end

  def calendar
  end

  def get_bookings
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = @cleaner.bookings
  end

  def get_booking
    @cleaner = Cleaner.find(current_user.actable_id)
    booking_html = render_to_string(:template => 'cleaners/bookings/_claim_booking.html.erb', :layout => false, :locals => { :booking => @booking })
    render :json => { :booking_html => booking_html }, :status => :ok
  end

  def email_bookings
    unless params['bookings'] == nil
      if params['date'] == 'today'
        Cleaner.find(current_user.actable_id).email_today_bookings(params['bookings'])
      else
        Cleaner.find(current_user.actable_id).email_tomorrow_bookings(params['bookings'])
      end
    end
    flash[:success] = "You bookings were emailed succesfully. Please review your email."
    redirect_to cleaners_dashboard_path
  end

  def accept_booking
    @booking.accept_request(current_user)
    if @booking.save
      flash[:success] = "You have succesfully accepted the customer request."
      redirect_to cleaners_dashboard_path
    end
  end

  def decline_booking
    @booking.decline_request(current_user)
    if @booking.save
      flash[:success] = "You have declined the customer request."
      redirect_to cleaners_dashboard_path
    end
  end

  private
    
  def set_booking
    @booking = Booking.find_by(id: params[:id])
  end
end

app/controllers/cleaners/dashboard_controller.rb
class Cleaners::DashboardController < ApplicationController
  
  def index 
    @cleaner = Cleaner.find(current_user.actable_id)
    @bookings = @cleaner.get_todays_bookings
    @future_bookings = @cleaner.get_assigned_bookings_for_tomorrow
  end
end

app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
	before_action :set_cleaner, only: [:edit, :update]

  def edit
  end

  def update
    if params[:cleaner][:password].blank? && params[:cleaner][:password_confirmation].blank?
      params[:cleaner].delete("password")
      params[:cleaner].delete("password_confirmation")
    end
    respond_to do |format|
      if @cleaner.update(cleaner_params)
        flash[:notice] = 'Cleaner was updated succesfully'
        format.html { redirect_to edit_cleaner_path(@cleaner) }
      else
        flash[:error] = @cleaner.errors
        format.html { render :edit }
      end
    end
  end

  def back_to_admin
    cleaner_user = current_user
    sign_out(cleaner_user)
    session["cleaner_session_id"] = nil
    admin = User.find(session["admin_session_id"])
    sign_in(:user, admin)
    redirect_to admin_dashboard_path
  end

  def destroy_admin_session
    @current_user = Cleaner.find(session["cleaner_session_id"])
    sign_out_and_redirect(@current_user)
  end

  private
    
    def set_cleaner
      @cleaner = Cleaner.find_by(id: current_user.actable_id)
    end

    def cleaner_params
      params.require(:cleaner).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :address, :postal_code, :state, :city, :max_bookings, :rating, :timezone, :role )
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def base_service(services)
    return services.select { |service| service.service_type == 'base' }.first
  end

  def params_service(services)
    service = services.select { |service| service.service_type == 'parameter' }.first
    return service ? service.name : 'No service parameter'
  end

  def extra_services(services)
    return services.select { |service| service.service_type == 'add_on' }
  end

  def show_address(booking, user)
    Time.current.utc.in_time_zone(user.timezone) >= (booking.booking_date.localtime - 1.day).to_time.change(hour: Config.fetch("show_adress_time").to_i).localtime ? true : false
  end

  def show_earnings_percetage(user, booking_amount)
    earnings = user.percentage_of_booking
    return earnings ? (((earnings * booking_amount ) / 100 ).to_f.round(2)) : 0
  end

  def show_area(zipcode)
    zipcode = zipcode.scan(/(.{1,5})/).flatten.first
    zipcode = Zipcode.find_by_number(zipcode)
    zipcode ? zipcode.area.name : 'No area found'
  end

  def show_time_left_to_claim(date, user)
    time = date.to_time.utc.in_time_zone(user.timezone) - Time.current.in_time_zone(user.timezone)
    time_left = (time / 60) - (Config.fetch('requested_booking_limit').to_i * 60) - (24 * 60)
    days = (time_left / (24 * 60)).to_i
    hours = (time_left / 60 - (days * 24)).to_i
    minutes = (time_left - (days * 24 * 60) - (hours * 60)).to_i
    return "#{days} days, #{hours} hours, #{minutes} minutes"
  end

  def show_cut_of_time
    start_time = Config.fetch('requested_booking_limit').to_i > 12 ? (Config.fetch('requested_booking_limit').to_i ) - 12 : (Config.fetch('requested_booking_limit').to_i )
    end_time = Config.fetch('cut_of_time').to_i > 12 ? Config.fetch('cut_of_time').to_i - 12 : Config.fetch('cut_of_time').to_i
    start_am_pm = Config.fetch('requested_booking_limit').to_i > 12 ? 'PM' : 'AM'
    end_am_pm = Config.fetch('cut_of_time').to_i > 12 ? 'PM' : 'AM'
    return "#{start_time} #{start_am_pm} today and #{end_time} #{end_am_pm} tomorrow"
  end
end

app/views/cleaners/bookings/_booking.html.erb
<div class="booking-holder">
  <div class="pa-ver-20 pa-hor-10 box-content">

    <div class="absolute-768 t-center booking-locations" style="margin-top: -10px">
      <p class="in-line bg-servus-blue bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.company.name %></p>
      <p class="in-line bg-servus-orange bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.location.name %></p>
    </div>

    <div class="row flex-768">
      <div class="col-sm-4">
        <div class="hor-align-center-768 pa-10 bo-ra-5 t-center width-50 f-size-150 bg-servus-green fo-servus-white vertical-align-center-768 relative-768 center ma-ver-10">
          <p><%= booking.booking_date.to_date.strftime("%B, %a %d, %Y") %></p>
          <p><%= booking.booking_date.strftime("%I:%M %p") %></p>  
        </div>
      </div>

      <div class="col-sm-8">
      
        <div class="booking-address-holder">
          
          <div class="booking-address ">
            <p>Customer: <%= booking.property.customer.full_name %></p>
            <p>Postal Code: <%= booking.property.postal_code %></p>
            <p>Area: <%= show_area(booking.property.postal_code) %></p>
            <% if booking.customer_notes %>
              <p>Customer Notes: <%= booking.customer_notes %> </p>
            <% end %>
          </div>

          <div class="row flex-768 block">
            <div class="col-sm-7">
              <p><strong>Services</strong></p>
              <p>Base Service: <%= base_service(booking.services).name if booking.services %></p>
              <p><%= params_service(booking.services) unless params_service(booking.services).blank? %></p>
              <ul>
                <% extra_services(booking.services).each do |service|%>
                  <li><%= service.name %></li>
                <% end %>
              </ul>  
            </div>
            <div class="col-sm-5 text-center">
              <p class="booking-price f-size-150 vertical-align-center-768 hor-align-center-768 absolute-768"> Your Earnings : $<%= show_earnings_percetage(@cleaner, booking.final_amount) %></p>
            </div>
          </div>
        </div>
      </div> 
    </div>
    <% unless booking.booking_assigned? %>
      <div class=" ma-ver-10 booking-btn-holder">
        <%= link_to "Claim Booking", cleaners_booking_path(booking), class: 'btn btn-info btn-lg', :method=> :put %>
      </div>
    <% end %>
  </div>
</div>

app/views/cleaners/bookings/_claim_booking.html.erb
<div class="booking-holder">
  <div class="pa-ver-20 pa-hor-10 box-content">

    <div class="absolute-768 t-center booking-locations" style="margin-top: -10px">
      <div class="xs-hidden">
        <span class="badge-job badge-recommended">
          <i class="fa fa-check" aria-hidden="true"></i>Job Requested
        </span>
      </div>
      <p class="in-line bg-servus-blue bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.company.name %></p>
      <p class="in-line bg-servus-orange bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.location.name %></p>
    </div>

    <div class="row flex-768">
      <div class="col-sm-4">

        <% if booking.requested? %>
          <div class="t-center xs-show">
            <span class="badge-job badge-recommended">
              <i class="fa fa-check" aria-hidden="true"></i>Job Requested
            </span>
          </div>
        <% end %>

        <div class="hor-align-center-768 pa-10 bo-ra-5 t-center width-50 f-size-150 bg-servus-green fo-servus-white vertical-align-center-768 relative-768 center ma-ver-10">
          <p><%= booking.booking_date.to_date.strftime("%B, %a %d, %Y") %></p>
          <p><%= booking.booking_date.strftime("%I:%M %p") %></p>  
        </div>
      </div>

      <div class="col-sm-8">
      
        <div class="booking-address-holder">
          
          <div class="booking-address ">
            <p>Customer: <%= booking.property.customer.full_name %></p>
            <p>Postal Code: <%= booking.property.postal_code %></p>
            <p>Area: <%= show_area(booking.property.postal_code) %></p>
            <% if booking.customer_notes %>
              <p>Customer Notes: <%= booking.customer_notes %> </p>
            <% end %>
          </div>

          <div class="row flex-768 block">
            <div class="col-sm-7">
              <p><strong>Services</strong></p>
              <p>Base Service: <%= base_service(booking.services).name if booking.services %></p>
              <p><%= params_service(booking.services) unless params_service(booking.services).blank? %></p>
              <ul>
                <% extra_services(booking.services).each do |service|%>
                  <li><%= service.name %></li>
                <% end %>
              </ul>  
            </div>
            <div class="col-sm-5 text-center">
              <p class="booking-price f-size-150 vertical-align-center-768 hor-align-center-768 absolute-768"> Your Earnings : $<%= show_earnings_percetage(@cleaner, booking.final_amount) %></p>
            </div>
          </div>
          <% if booking.is_past_booking? && !booking.requested?  %>
            <div>
              <%= link_to 'View This Booking', cleaners_booking_path(booking), class: 't-no-decoration' %>
            </div>
          <% end %>
        </div>
      </div> 
    </div>
    <!-- If the Booking is still requested, show accept and deny -->
    <% if booking.requested? %>
      <div class="t-center pa-ver-20 requested_booking">
        <p class="ma-ver-20 f-size-150 bold">Time left to claim: <%= show_time_left_to_claim(booking.booking_date.localtime.to_time, @cleaner) %> </p>
        <%= link_to 'Accept Request', accept_booking_cleaners_booking_path(booking), class: 'btn btn-success btn-lg ma-ver-10', :method=> :post  %>
        <%= link_to "Decline Request", decline_booking_cleaners_booking_path(booking), class: 'btn btn-danger btn-lg ma-ver-10', :method=> :post %>
      </div>
    <% end %>

    <!-- If booking is assigned, show cancelation -->
    <% if booking.booking_assigned? %>
      <div class="ma-ver-10 booking-btn-holder">
        <% if booking.can_cancel_booking? %>
          <div class="booking-btn-holder">
            <%= link_to "Cancel Booking", cancel_booking_cleaners_booking_path(booking), class: 'btn btn-danger btn-lg', :method=> :post %>
          </div>
        <% else %>    
          <div class="booking-btn-holder">    
            <button id="cancel_booking" type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#myModalCancellation"  data-backdrop="static">Cancel Booking</button>    
          </div>    
          <%= render 'cleaners/shared/cancelation_modal', booking: booking %>   
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cleaners/bookings/calendar.html.erb
<section class="app-content">
  <div class="container">
    
    <!-- Booking Information -->
    <div class="cleaner-wrapper box-wrapper">
      <div class="cleaner-header bo-grey">
        <p>Calendar</p>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div id="calendar" style="margin: 2rem"></div>

          <!-- Modal Edit/Delete Event-->
          <div class="modal fade" id="BookingInfo" tabindex="-1" role="dialog" aria-labelledby="EditDeleteEventLabel">
            <div class="modal-dialog" role="document" id="calendar_dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="BookingInfoLabel">Booking</h4>
                </div>

                <div class="modal-body">
                  <div class="row">
                    <div class="col-sm-12" id="booking"></div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</section>

app/views/cleaners/bookings/index.html.erb
<section class="app-content">
  <div class="container">
    <!-- Booking Filter -->
    <div class="cleaner-wrapper box-wrapper">
      <div class="cleaner-header bo-grey">
        <p>Filter</p>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="booking-holder box-content">
            <div class="pa-ver-20 pa-hor-10">
              <%= link_to "6AM to 10AM", {:controller => :bookings, :action => :index, :from => 6, :to => 10 }, class:'btn btn-default' %>

              <%= link_to "11AM to 3PM", {:controller => :bookings, :action => :index, :from => 11, :to => 15 }, class:'btn btn-default' %>

              <%= link_to "4PM to Midnight", {:controller => :bookings, :action => :index, :from => 15, :to => 24 }, class:'btn btn-default' %>

              <%= link_to "Clear", {:controller => :bookings, :action => :index }, class:'btn btn-default' %>
            </div>
          </div>
        </div>
      </div>
    </div> 
    <!-- Booking Information -->
    <div class="cleaner-wrapper box-wrapper">
      <div class="cleaner-header bo-grey">
        <p>Available Bookings</p>
        <p class="bold">You can claim <%= @cleaner.bookings_left_to_claim_by_date(Time.current.utc.in_time_zone(@cleaner.timezone).beginning_of_day + 2.day, Time.current.utc.in_time_zone(@cleaner.timezone).beginning_of_day + 2.day ) %> more bookings for <%= (Time.current.utc.in_time_zone(@cleaner.timezone) + 2.day).strftime("%A %d, %B, %Y") %> </p>
        <p> Claim your bookings between <%= show_cut_of_time %> </p>
      </div>
      <div class="row">
        <div class="col-md-12" id="results">
          <% if @cleaner.can_claim_booking? %>
            <% if !@bookings.empty? && @cleaner.has_permission_to_view? && @cleaner.cut_of_time %>
              <% @bookings.each do |booking| %>
                <%= render 'booking', booking: booking %>
              <% end %>
              <div class="t-center">
                <%= paginate @bookings %>    
              </div>
            <% else %>
              <div class="booking-holder">
                <div class="pa-ver-20 pa-hor-10 box-content">
                  <p class="text-center">There are no bookings available to claim.</p>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="booking-holder">
              <div class="pa-ver-20 pa-hor-10 box-content">
                <p class="text-center">You have reached the max amount of bookings that you can claim for tomorrow.</p>
                <p class="text-center">
                  <%= link_to 'Check your Bookings', cleaners_dashboard_path, class: "btn btn-success ma-ver-20"%>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/cleaners/bookings/previous.html.erb
<section class="app-content">
  <div class="container">
    
    <!-- Booking Information -->
    <div class="cleaner-wrapper box-wrapper">
      <div class="cleaner-header bo-grey">
        <p>Previous Bookings</p>
      </div>
      <div class="row">
        <div class="col-md-12">
          <% unless @bookings.empty? %>
            <% @bookings.each do |booking| %>
              <div class="booking-holder">
                <div class="pa-ver-20 pa-hor-10 box-content">

                  <div class="absolute-768 t-center booking-locations" style="margin-top: -10px">
                    <p class="in-line bg-servus-blue bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.company.name %></p>
                    <p class="in-line bg-servus-orange bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= booking.location.name %></p>
                  </div>

                  <div class="row flex-768">
                    <div class="col-sm-4">
                      <div class="hor-align-center-768 pa-10 bo-ra-5 t-center width-50 f-size-150 bg-servus-green fo-servus-white vertical-align-center-768 relative-768 center ma-ver-10">
                        <p><%= booking.booking_date.to_date.strftime("%B, %a %d, %Y") %></p>
                        <p><%= booking.booking_date.localtime.strftime("%I:%M %p") %></p>  
                      </div>  
                    </div>

                    <div class="col-sm-8">
                    
                      <div class="booking-address-holder">
                        
                        <div class="booking-address ">
                          <p>Address: <%= booking.property.full_address %></p>
                          <p>Area: <%= show_area(booking.property.postal_code) %></p>
                        </div>

                        <div class="row flex-768 block">
                          <div class="col-sm-7">
                            <p><strong>Services</strong></p>
                            <p>Base Service: <%= base_service(booking.services).name %></p>
                            <p><%= params_service(booking.services) %></p>
                            <ul>
                              <% extra_services(booking.services).each do |service|%>
                                <li><%= service.name %></li>
                              <% end %>
                            </ul>  
                          </div>
                          <div class="col-sm-5 text-center">
                            <p class="booking-price f-size-150 vertical-align-center-768 hor-align-center-768 absolute-768"> Your Earnings : $<%= show_earnings_percetage(@cleaner, booking.final_amount) %></p>
                          </div>
                        </div>

                        <div>
                          <%= link_to 'View This Booking', cleaners_booking_path(booking), class: 't-no-decoration' %>
                        </div>
                      </div>
                    </div> 
                  </div>
                </div>
              </div>
            <% end %>
            <div class="t-center">
              <%= paginate @bookings %>    
            </div>
          <% else %>
            <div class="booking-holder">
              <div class="pa-ver-20 pa-hor-10 box-content">
                <p class="text-center">You don't have any previous booking.</p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div> 
  </div>
</section>

app/views/cleaners/bookings/show.html.erb
<section class="app-content">
  <div class="container">   
    <!-- Booking Information -->
    <div class="cleaner-wrapper box-wrapper">

      <div class="row">
        <div class="col-md-12">
          <div class="booking-holder">
            <div class="pa-ver-20 pa-hor-10 box-content">
              <div >
                <div class="bo-grey bo-ra-5 pa-ver-20 pa-hor-20">
                  <p class="in-line bg-servus-blue bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= @booking.company.name %></p>
                  <p class="in-line bg-servus-orange bo-ra-5 pa-ver-5 pa-hor-10 fo-servus-white"><%= @booking.location.name %></p>
                  <h1 class="f-size-150 ma-ver-10 ">Booking Information</h1>
                  <p>Booking Date: <%= @booking.booking_date.to_date.strftime("%B, %a %d, %Y") %></p>
                  <p>Time:<%= @booking.booking_date.localtime.strftime("%I:%M %p") %></p>  
                  <p>Customer_notes</p>
                  <% if @booking.rating_value %>
                    <p>Rating Value: <%= @booking.rating_value %></p>
                  <% end %>
                  <p>Your Earnings : $<%= show_earnings_percetage(@cleaner, @booking.final_amount) %></p>
                  <% if @booking.tip %>
                    <p>Tip: <%= @booking.tip %></p>
                  <% end %>
                </div>

                <div class="bo-grey bo-ra-5 pa-ver-20 pa-hor-20">
                  <h1 class="f-size-150 ma-ver-10 ">Service Information</h1>
                  <p><strong>Services:</strong></p>
                  <p>Base Service: <%= base_service(@booking.services).name %></p>
                  <p><%= params_service(@booking.services) %></p>
                  <ul>
                    <% extra_services(@booking.services).each do |service|%>
                      <li><%= service.name %></li>
                    <% end %>
                  </ul>
                </div>
                <div class="bo-grey bo-ra-5 pa-ver-20 pa-hor-20">
                  <h1 class="f-size-150 ma-ver-10 ">Customer Information</h1>
                  <p>Customer: <%= @booking.property.customer.full_name %></p>
                  <p>Address: <%= @booking.property.full_address %></p>
                  <p>Area: <%= show_area(@booking.property.postal_code) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</section>