config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#index'
    # get '/cleaners/sign_in', to: 'devise/sessions#new'
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path: '', path_names: { sign_in: 'cleaners/sign_in', sign_out: '/users/sign_out' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post '/register/cleaner', to: 'users/registrations#create_cleaner'
  end

  mount Resque::Server, at: "/resque"
  # For running resque queues it must be redis server running
  # Run this line in terminal
  # QUEUE=* rake resque:work

  namespace :cleaners do
    get "/dashboard", to: "dashboard#index"
    get '/calendar', to: "bookings#calendar"
    get "/calendar/booking", to: "bookings#get_booking"
    get "/calendar/bookings", to: "bookings#get_bookings"
    resources :bookings do 
      post 'cancel_booking', to: "bookings#cancel_booking", on: :member
      post 'accept_booking', to: "bookings#accept_booking", on: :member
      post 'decline_booking', to: "bookings#decline_booking", on: :member
      get 'email_booking', to: "bookings#email_bookings", on: :collection
      get 'previous', to: "bookings#previous",  on: :collection
    end
  end

  resources :cleaners do
    get "/back_to_admin", to: "cleaners#back_to_admin", as: "back_to_admin", on: :collection
    get "/destroy_admin_session", to: "cleaners#destroy_admin_session", as: "destroy_admin_session", on: :collection
  end

  scope '/webhooks' do
    post 'new_booking', to: 'webhooks#new_booking'
    post 'cancel_booking', to: 'webhooks#cancel_booking'
    post 'complete_booking', to: 'webhooks#complete_booking'
    post 'update_booking', to: 'webhooks#update_booking'
  end
end

app/views/layouts/_header.html.erb
<section class="app-header">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <h1>Servus</h1>
        </a>
      </div>
      <% if user_signed_in? %>
            
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">

          <li class="ma-ver-5">
            <%= link_to root_path, class: 'nav-link inside bo-none' do %>
              <i class="fa fa-book" aria-hidden="true"></i>My Bookings 
            <% end %>
          </li>

          <li class="ma-ver-5">
            <%= link_to cleaners_bookings_path, class: 'nav-link inside bo-none' do %>
              <i class="fa fa-address-book-o" aria-hidden="true"></i>Claim Bookings 
            <% end %>
          </li>

          <li class="ma-ver-5" >
            <%= link_to previous_cleaners_bookings_path, class: 'nav-link inside bo-none' do %>
              <i class="fa fa-calendar-check-o"></i>Previous Bookings
            <% end %>
          </li>

          <li class="ma-ver-5" >
            <%= link_to cleaners_calendar_path, class: 'nav-link inside bo-none' do %>
              <i class="fa fa-calendar"></i>Calendar
            <% end %>
          </li>

          <li class="dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i>Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to('Edit Profile', edit_cleaner_path(current_user), class: "nav-link inside") %> 
              </li>
              <% if session["admin_session_id"].nil? %>
                <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => 'delete', class: "nav-link inside") %> 
                </li>
              <% end %>
              <% unless session["admin_session_id"].nil? %>
                <li>
                  <%= link_to 'Go back to Admin', back_to_admin_cleaners_path, class: "nav-link inside" %>
                </li>
                <li>
                  <%= link_to('Logout', destroy_admin_session_cleaners_path, class: "nav-link inside") %> 
                </li>
              <% end %>
            </ul>
          </li>

        </ul>
      </div><!-- /.navbar-collapse -->
      <% end %>
    </div>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Servus</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://use.fontawesome.com/6d179c63a6.js"></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="<%= controller.controller_name%>-<%=action_name%> alert fade in alert-<%= message_type%> container">
          <button class="close" data-dismiss="alert">&times;</button>
          <div class="show-flash" data-message="<%= message %>"><%= message %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
    

    <% if request.base_url == 'http://servuspros.com' %>
      <!-- Hotjar Tracking Code for servuspros.com -->
      <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:697636,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
      </script>
    <% end %>

  </body>

</html>